# Set hardware part number
CONFIG_MCUX_HW_DEVICE_PART_MIMXRT1011DAE5A=y

# Disable board files (clock, pinmux, hw app)
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n

# Use board suite (linker scripts, flags, etc.)
CONFIG_MCUX_PRJSEG_module.board.suite=y

# Use device and board FlexSPI NOR boot config headers
CONFIG_MCUX_COMPONENT_device.boot_header=y
CONFIG_MCUX_COMPONENT_board.boot_header=y
